version: '3.9'
services:
  app-nginx:
    image: nginx
    container_name: app-nginx
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - USUARIO=jose
      - PASSWD=1234
    networks:
        red_principal:
            ipv4_address: 172.16.1.10
  mongo:
    image: mongo:4.2
    container_name: mongo
    build:
      context: .
      dockerfile: ./docker-mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=josec
      - MONGO_INITDB_ROOT_PASSWORD=valadre
    ports:
      - '27017:27017'
    volumes: 
      - ./data:/data/db
    networks:
        red_principal:
            ipv4_address: 172.16.1.20

  servidor3:
    image: base
    container_name: servidor3
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - USUARIO=jose
      - PASSWD=1234
    networks:
        red_principal:
            ipv4_address: 172.16.1.30
  servidor4:
    image: base
    container_name: servidor4
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - USUARIO=jose
      - PASSWD=1234
    networks:
        red_principal:
            ipv4_address: 172.16.1.40
networks:
  red_principal:
    external: true
  mongo-compose-network:
    driver: bridge